# snow_obs_comparison.jl
#
# Compares the Julia microclimate model against NicheMapR predictions and SNOTEL 329
# field observations (snow depth, soil temperatures, soil moisture) for a 1-year run
# at SNOTEL site 329, Utah (39.14°N, 111.56°W, 2435 m), 2013-01-01 to 2013-12-31.
#
# NicheMapR outputs in test/data/scan329/nmr_hourly.csv are generated by
# prepare_scan329_data.jl, which runs NicheMapR with the same forcing as Julia.
#
# Run manually (not in CI — requires test/data/scan329/ data files):
#   julia test/snow_obs_comparison.jl
#
# Generate test/data/scan329/ first by running:
#   julia test/prepare_scan329_data.jl

using Microclimate
using SolarRadiation
using FluidProperties
using Unitful
using CSV, DataFrames, Dates
using Test

testdir = @__DIR__
datadir = joinpath(testdir, "data", "scan329")

# ── Load NicheMapR comparison data ────────────────────────────────────────────
nmr = DataFrame(CSV.File(joinpath(datadir, "nmr_hourly.csv")))

# ── Hard-wired site constants (SNOTEL 329, Utah) ─────────────────────────────
# Derived from micro csv input/microinput.csv
const ELEVATION   = 2435.35u"m"
const LATITUDE    = (39.0 + 8.2098 / 60.0)u"°"       # 39.1368°N
const LONGITUDE   = -(111.0 + 33.4878 / 60.0)u"°"    # 111.5580°W
const RUF         = 0.004u"m"
const USRHYT      = 0.01u"m"
const REFHYT      = 2.0u"m"
const ALBEDO      = 0.15                               # REFLS (constant all days)
const EMISSIVITY  = 0.95                               # SLES (constant)
const TANNUL      = 6.43                               # deep soil temperature (°C, constant)
const NDAYS       = 365

# Soil depths: 10 coarse nodes [0, 2.5, 5, 10, 15, 20, 30, 50, 100, 200] cm expanded to
# 19 fine nodes by inserting midpoints (same scheme as micro_testrun_daily.jl):
# [0, 1.25, 2.5, 3.75, 5, 7.5, 10, 12.5, 15, 17.5, 20, 25, 30, 40, 50, 75, 100, 150, 200] cm
const DEPTHS = ([0.0, 1.25, 2.5, 3.75, 5.0, 7.5, 10.0, 12.5, 15.0, 17.5,
                 20.0, 25.0, 30.0, 40.0, 50.0, 75.0, 100.0, 150.0, 200.0] ./ 100.0) .* u"m"

# Soil properties — all from micro csv input/ files written by NicheMapR (write_input=1)
# 19 fine nodes, properties interpolated (midpoints averaged) from 10 coarse soilprop.csv rows
const BULK_DENSITY        = 1.3u"Mg/m^3"                   # BD.csv (uniform)
const SATURATION_MOISTURE = 0.4922u"m^3/m^3"               # soilprop.csv col 2 (uniform)
const MINERAL_DENSITY     = 2.56u"Mg/m^3"                  # DD.csv (uniform)
# Thermal: soilprop.csv cols 3-4 — nodes 1-3 shallow (k=0.2, cp=1920), node 4 transition,
#          nodes 5-19 deeper mineral (k=2.5, cp=870); midpoint node 4 is average of rows 2 & 3
const MINERAL_CONDUCTIVITY  = [0.2, 0.2, 0.2, 1.35, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5,
                                2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]u"W/m/K"
const MINERAL_HEAT_CAPACITY = [1920.0, 1920.0, 1920.0, 1395.0, 870.0, 870.0, 870.0, 870.0, 870.0, 870.0,
                                870.0, 870.0, 870.0, 870.0, 870.0, 870.0, 870.0, 870.0, 870.0]u"J/kg/K"
const DE_VRIES_SHAPE_FACTOR = 0.1                           # SOILPROPS.f:207 — 0.1 for mineral soil
                                                            # (microinput.csv row 25 is `EC` = orbital eccentricity, not de Vries g_a)
# Hydraulic: PE.csv, KS.csv, BB.csv (uniform — all 19 rows identical)
const AIR_ENTRY_POTENTIAL   = 1.1u"J/kg"                    # PE.csv
const SAT_HYDRAULIC_COND    = 0.0037u"kg*s/m^3"             # KS.csv
const CAMPBELL_B            = 4.5                            # BB.csv
# Root length density: L.csv all 19 rows (m/m³)
const ROOT_DENSITY = [0.0, 0.0, 82000.0, 80000.0, 78000.0, 74000.0, 71000.0, 64000.0, 58000.0, 48000.0,
                      40000.0, 18000.0, 9000.0, 6000.0, 8000.0, 4000.0, 4000.0, 0.0, 0.0]u"m/m^3"

# Initial soil moisture (m³/m³) from micro csv input/moists.csv column 2 — 10 coarse nodes.
# Expand to 19 fine nodes by inserting midpoints (average of neighbours), same as micro_testrun_daily.jl.
const _INITIAL_SM_COARSE = DataFrame(CSV.File(joinpath(datadir, "initial_sm.csv"))).moisture
const INITIAL_SM = let coarse = _INITIAL_SM_COARSE, n = length(coarse)
    result = Vector{Float64}(undef, 2n - 1)
    for i in 1:n;     result[2i-1] = coarse[i]; end
    for i in 1:n-1;   result[2i]   = (coarse[i] + coarse[i+1]) / 2; end
    result
end
INITIAL_ST = fill(274.15u"K", length(DEPTHS))
INITIAL_ST[19] = (273.15 + 6.4)u"K"
INITIAL_ST[18] = (273.15 + (6.4 + 3.0) / 2.0)u"K"
INITIAL_ST[17] = (273.15 + 3)u"K"
INITIAL_ST[16] = (273.15 + 3)u"K"
INITIAL_ST[15] = (273.15 + 3)u"K"


# ── Load daily forcing ────────────────────────────────────────────────────────
forcing = DataFrame(CSV.File(joinpath(datadir, "forcing.csv")))
days2do = 1:NDAYS

# ── Terrain ───────────────────────────────────────────────────────────────────
micro_terrain = MicroTerrain(;
    elevation      = ELEVATION,
    roughness_height = RUF,
    karman_constant  = 0.4,
    dyer_constant    = 16.0,
    viewfactor       = 1.0,
)

solar_terrain = SolarTerrain(;
    slope              = 0.0u"°",
    aspect             = 0.0u"°",
    elevation          = ELEVATION,
    horizon_angles     = zeros(24)u"°",
    albedo             = ALBEDO,
    atmospheric_pressure = atmospheric_pressure(ELEVATION),
    latitude           = LATITUDE,
    longitude          = LONGITUDE,
)

# ── Soil models ───────────────────────────────────────────────────────────────
soil_thermal_model = CampbelldeVriesSoilThermal(;
    bulk_density          = BULK_DENSITY,
    mineral_density       = MINERAL_DENSITY,
    de_vries_shape_factor = DE_VRIES_SHAPE_FACTOR,
    mineral_conductivity  = MINERAL_CONDUCTIVITY,
    mineral_heat_capacity = MINERAL_HEAT_CAPACITY,
    saturation_moisture   = SATURATION_MOISTURE,
    recirculation_power   = 4.0,
    return_flow_threshold = 0.162,
)

soil_moisture_model = example_soil_hydraulics(DEPTHS;
    bulk_density                     = BULK_DENSITY,
    mineral_density                  = MINERAL_DENSITY,
    air_entry_water_potential        = fill(AIR_ENTRY_POTENTIAL, length(DEPTHS)),
    saturated_hydraulic_conductivity = fill(SAT_HYDRAULIC_COND, length(DEPTHS)),
    campbell_b_parameter             = fill(CAMPBELL_B, length(DEPTHS)),
    root_density                     = ROOT_DENSITY,
    mode                             = DynamicSoilMoisture(),
)

# ── Daily min/max environment (1461 days) ─────────────────────────────────────
# RHMINN/RHMAXX and CCMAXX are in %; divide by 100 for fractional
environment_minmax = DailyMinMaxEnvironment(;
    reference_temperature_min = forcing.TMINN[days2do] .* u"°C",
    reference_temperature_max = forcing.TMAXX[days2do] .* u"°C",
    reference_wind_min        = forcing.WNMINN[days2do] .* u"m/s",
    reference_wind_max        = forcing.WNMAXX[days2do] .* u"m/s",
    reference_humidity_min    = forcing.RHMINN[days2do] ./ 100.0,
    reference_humidity_max    = forcing.RHMAXX[days2do] ./ 100.0,
    cloud_min                 = zeros(NDAYS),
    cloud_max                 = forcing.CCMAXX[days2do] ./ 100.0,
    minima_times              = [0.0, 0.0, 1.0, 1.0],  # TIMINS1-4
    maxima_times              = [1.0, 1.0, 0.0, 0.0],  # TIMAXS1-4
)

# ── Daily timeseries ──────────────────────────────────────────────────────────
environment_daily = DailyTimeseries(;
    shade                 = zeros(NDAYS),
    soil_wetness          = zeros(NDAYS),
    surface_emissivity    = fill(EMISSIVITY, NDAYS),
    cloud_emissivity      = fill(EMISSIVITY, NDAYS),
    rainfall              = forcing.RAINFALL[days2do] .* u"kg/m^2",
    # Mirror R's tannulrun (micro_usa.R:1099-1115): 365-day trailing rolling mean of
    # daily (TMAX+TMIN)/2. Days 1-365 use the simple mean of days 1-365; from day 366
    # onward use the trailing 365-day window. This is the per-day deep-soil boundary
    # Fortran reads via TANNULRUN(IDAY) (SOLRAD.f:1253) → TDS (SINEC.f:132).
    deep_soil_temperature = let
        avetemp = (forcing.TMAXX[days2do] .+ forcing.TMINN[days2do]) ./ 2
        n = length(avetemp)
        tannulrun = Vector{Float64}(undef, n)
        if n >= 365
            yearone_mean = sum(view(avetemp, 1:365)) / 365
            for i in 1:min(365, n); tannulrun[i] = yearone_mean; end
            for i in 366:n
                tannulrun[i] = sum(view(avetemp, (i - 364):i)) / 365
            end
        else
            fill!(tannulrun, sum(avetemp) / n)
        end
        tannulrun .* u"°C"
    end,
    leaf_area_index       = fill(0.1, NDAYS),
)

# ── Hourly placeholder (pressure only) ───────────────────────────────────────
environment_hourly = HourlyTimeseries(;
    pressure              = fill(atmospheric_pressure(ELEVATION), NDAYS * 24),
    reference_temperature = nothing,
    reference_humidity    = nothing,
    reference_wind_speed  = nothing,
    global_radiation      = nothing,
    cloud_cover           = nothing,
    rainfall              = nothing,
    zenith_angle          = nothing,
    longwave_radiation    = nothing,
)

solar_model = SolarProblem(; scattered_uv = false)

snow_model = SnowModel(;
    snow_temperature_threshold = 1.5u"°C",
    snow_density = 0.375u"g/cm^3",
    snow_melt_factor = 1.0,
    undercatch = 1.0,
    rain_multiplier = 1.0,
    rain_melt_factor = 0.0125,
    density_function = (0.5979, 0.2178, 0.001, 0.0038),
    snow_conductivity = 0.0u"W/m/K",
    canopy_interception = 0.0,
)

# ── Build and solve ───────────────────────────────────────────────────────────
problem = MicroProblem(;
    latitude              = LATITUDE,
    days                  = forcing.DOY[days2do],
    hours                 = collect(0.0:1:23.0),
    depths                = DEPTHS,
    heights               = [USRHYT, REFHYT],
    solar_model,
    solar_terrain,
    micro_terrain,
    soil_moisture_model,
    soil_thermal_model,
    environment_minmax,
    environment_daily,
    environment_hourly,
    time_mode             = ConsecutiveDayMode(; spinup_first_day=false),
    convergence           = FixedSoilTemperatureIterations(3),
    hourly_rainfall       = false,
    snow_model,
    initial_soil_temperature = INITIAL_ST,
    initial_soil_moisture = Vector{Float64}(INITIAL_SM),
    #initial_snow_depth = 78.0u"cm",
    #initial_snow_temperature = u"K"(0.0u"°C"),
)

println("Running Julia microclimate model for $NDAYS days (2013)...")
@time micro_out = Microclimate.solve(problem)
println("Simulation complete.")

# ── Load SNOTEL 329 observations ──────────────────────────────────────────────
obs = DataFrame(CSV.File(joinpath(datadir, "obs.csv"),
    missingstring = ["NA", ""],
))
# Older snapshots of obs.csv use the column name `WTEQ_in10`; rename for forward compatibility
if "WTEQ_in10" in String.(propertynames(obs)) && !("WTEQ_in" in String.(propertynames(obs)))
    rename!(obs, :WTEQ_in10 => :WTEQ_in)
end
# DateTime column is auto-parsed by CSV
# Unit notes: SNWD_mm = snow depth in inches (×2.54 → cm), WTEQ_in = SWE in inches (×2.54 → cm)
#   Soil temps STO_*cm in °C, soil moisture SMS_*cm in %

# ── Comparisons ───────────────────────────────────────────────────────────────
# Extract Julia soil temperatures at key depths
# 19-node DEPTHS index: 5=5cm, 7=10cm, 11=20cm, 15=50cm, 17=100cm, 19=200cm (1-indexed)
julia_D5cm  = ustrip.(u"°C", micro_out.soil_temperature[:, 5])
julia_D20cm = ustrip.(u"°C", micro_out.soil_temperature[:, 11])
julia_D50cm = ustrip.(u"°C", micro_out.soil_temperature[:, 15])

julia_WC5cm  = micro_out.soil_moisture[:, 5]
julia_WC20cm = micro_out.soil_moisture[:, 11]
julia_WC50cm = micro_out.soil_moisture[:, 15]

nhours_out = NDAYS * 24
nmr_sub = nmr[1:nhours_out, :]

# ── Detailed node diagnostics at a snow-covered hour ─────────────────────────
# Pick hour 12 of day 60 (deep snow period, week 9)
diag_step = (60 - 1) * 24 + 12
println("\n── Node temperatures at step $diag_step (day 60, hour 12) ──")
println("Snow depth: ", ustrip(u"cm", micro_out.snow_depth[diag_step]), " cm")
println("Snow density: ", ustrip(u"g/cm^3", micro_out.snow_density[diag_step]), " g/cm³")
println("Soil node temperatures (all depths):")
for (k, d) in enumerate(DEPTHS)
    st = ustrip(u"°C", micro_out.soil_temperature[diag_step, k])
    tc = ustrip(u"W/m/K", micro_out.soil_thermal_conductivity[diag_step, k])
    hc = ustrip(u"J/kg/K", micro_out.soil_heat_capacity[diag_step, k])
    bd = ustrip(u"kg/m^3", micro_out.soil_bulk_density[diag_step, k])
    sm = micro_out.soil_moisture[diag_step, k]
    println("  depth=$(ustrip(u"cm",d))cm: T=$(round(st,digits=3))°C  k=$(round(tc,digits=4))  cp=$(round(hc,digits=1))  rho=$(round(bd,digits=1))  SM=$(round(sm,digits=4))")
end
println("NicheMapR at same step: D5cm=$(nmr.D5cm[diag_step])  D20cm=$(nmr.D20cm[diag_step])  D50cm=$(nmr.D50cm[diag_step])  snow=$(nmr.SNOWDEP[diag_step])cm")

# ── Diagnostic summary ──────────────────────────────────────────────────────
snow_depth_julia   = ustrip.(u"cm",     micro_out.snow_depth)
snow_density_julia = ustrip.(u"g/cm^3", micro_out.snow_density)

println("\n── Diagnostic summary (first $NDAYS days) ──")
println("Soil temp 5cm  — Julia range: ", extrema(julia_D5cm), "  NicheMapR range: ", extrema(nmr_sub.D5cm))
println("Soil temp 20cm — Julia range: ", extrema(julia_D20cm), "  NicheMapR range: ", extrema(nmr_sub.D20cm))
println("Soil temp 50cm — Julia range: ", extrema(julia_D50cm), "  NicheMapR range: ", extrema(nmr_sub.D50cm))
println("Snow depth     — Julia range: ", extrema(snow_depth_julia), "  NicheMapR range: ", extrema(nmr_sub.SNOWDEP))
println("Snow density   — Julia range: ", extrema(snow_density_julia), "  NicheMapR range: ", extrema(nmr_sub.SNOWDENS))

# Check where biggest divergences occur
diff_5cm = julia_D5cm .- nmr_sub.D5cm
diff_20cm = julia_D20cm .- nmr_sub.D20cm
diff_50cm = julia_D50cm .- nmr_sub.D50cm
diff_snow = snow_depth_julia .- nmr_sub.SNOWDEP

println("\nSoil temp 5cm  diff — mean: ", round(sum(diff_5cm)/length(diff_5cm), digits=3), "  max abs: ", round(maximum(abs.(diff_5cm)), digits=3))
println("Soil temp 20cm diff — mean: ", round(sum(diff_20cm)/length(diff_20cm), digits=3), "  max abs: ", round(maximum(abs.(diff_20cm)), digits=3))
println("Soil temp 50cm diff — mean: ", round(sum(diff_50cm)/length(diff_50cm), digits=3), "  max abs: ", round(maximum(abs.(diff_50cm)), digits=3))
println("Snow depth diff    — mean: ", round(sum(diff_snow)/length(diff_snow), digits=3), "  max abs: ", round(maximum(abs.(diff_snow)), digits=3))

# Show a few time slices where divergence is large
worst_idx_5cm = argmax(abs.(diff_5cm))
worst_day_5cm = div(worst_idx_5cm - 1, 24) + 1
worst_hr_5cm = mod(worst_idx_5cm - 1, 24)
println("\nWorst 5cm divergence at step $worst_idx_5cm (day $worst_day_5cm, hour $worst_hr_5cm):")
println("  Julia: $(julia_D5cm[worst_idx_5cm])°C  NicheMapR: $(nmr_sub.D5cm[worst_idx_5cm])°C  Snow: $(snow_depth_julia[worst_idx_5cm])cm vs $(nmr_sub.SNOWDEP[worst_idx_5cm])cm")

worst_idx_snow = argmax(abs.(diff_snow))
worst_day_snow = div(worst_idx_snow - 1, 24) + 1
worst_hr_snow = mod(worst_idx_snow - 1, 24)
println("\nWorst snow depth divergence at step $worst_idx_snow (day $worst_day_snow, hour $worst_hr_snow):")
println("  Julia: $(snow_depth_julia[worst_idx_snow])cm  NicheMapR: $(nmr_sub.SNOWDEP[worst_idx_snow])cm")

# Show weekly averages to see trends
println("\n── Weekly soil temp 5cm comparison ──")
for w in 1:min(26, div(NDAYS, 7))
    r = ((w-1)*7*24+1):min(w*7*24, nhours_out)
    j_avg = round(sum(julia_D5cm[r])/length(r), digits=2)
    n_avg = round(sum(nmr_sub.D5cm[r])/length(r), digits=2)
    s_j = round(sum(snow_depth_julia[r])/length(r), digits=2)
    s_n = round(sum(nmr_sub.SNOWDEP[r])/length(r), digits=2)
    println("  Week $w: Julia=$(j_avg)C  NMR=$(n_avg)C  (snow: J=$s_j  N=$s_n cm)")
end

# ── Daily melt summary during divergence period ──
println("\n── Daily snow depth and melt summary (days 78-112) ──")
println("  day | J_snow  N_snow | J_daily_Δ  N_daily_Δ | J_T0surf  N_T5cm")
for day in 78:112
    step_start = (day - 1) * 24 + 1
    step_end = day * 24
    (step_start > nhours_out || step_end > nhours_out) && continue
    j_snow_end = snow_depth_julia[step_end]
    n_snow_end = nmr_sub.SNOWDEP[step_end]
    j_snow_prev = day > 1 ? snow_depth_julia[(day-2)*24 + 24] : 0.0
    n_snow_prev = day > 1 ? nmr_sub.SNOWDEP[(day-2)*24 + 24] : 0.0
    j_daily = j_snow_end - j_snow_prev
    n_daily = n_snow_end - n_snow_prev
    # Soil surface temp at noon
    noon_step = (day - 1) * 24 + 13
    j_tsurf = ustrip(u"°C", micro_out.soil_temperature[noon_step, 1])
    n_t5 = nmr_sub.D5cm[noon_step]
    println("  $(lpad(day,3)) | $(lpad(round(j_snow_end,digits=1),6))  $(lpad(round(n_snow_end,digits=1),6)) | $(lpad(round(j_daily,digits=1),9))  $(lpad(round(n_daily,digits=1),9)) | $(lpad(round(j_tsurf,digits=2),7))  $(lpad(round(n_t5,digits=1),5))")
end

# ── Soil moisture and thermal property comparison ──
println("\n── Soil moisture & conductivity comparison ──")
println("  day | SM5_J SM5_N | SM20_J SM20_N | SM50_J SM50_N | k5_J   k20_J   k50_J")
for day in [90, 180, 270, 360, 450, 540, 730, 1000]
    step = (day-1)*24 + 13
    (step > nhours_out || step > size(nmr_sub, 1)) && continue
    j5 = round(micro_out.soil_moisture[step, 5], digits=3)
    j20 = round(micro_out.soil_moisture[step, 11], digits=3)
    j50 = round(micro_out.soil_moisture[step, 15], digits=3)
    n5 = round(nmr_sub.WC5cm[step], digits=3)
    n20 = round(nmr_sub.WC20cm[step], digits=3)
    n50 = round(nmr_sub.WC50cm[step], digits=3)
    k5 = round(ustrip(u"W/m/K", micro_out.soil_thermal_conductivity[step, 5]), digits=3)
    k20 = round(ustrip(u"W/m/K", micro_out.soil_thermal_conductivity[step, 11]), digits=3)
    k50 = round(ustrip(u"W/m/K", micro_out.soil_thermal_conductivity[step, 15]), digits=3)
    println("  $(lpad(day,4)) | $j5  $n5 | $j20  $n20 | $j50  $n50 | $k5  $k20  $k50")
end

# @testset "SNOTEL 329 — Julia vs NicheMapR ($(NDAYS)d)" begin
#     @test size(micro_out.soil_temperature, 1) == nhours_out
#     @test size(micro_out.soil_temperature, 2) == length(DEPTHS)

#     @test julia_D5cm  ≈ nmr_sub.D5cm  rtol=0.3
#     @test julia_D20cm ≈ nmr_sub.D20cm rtol=0.2
#     @test julia_D50cm ≈ nmr_sub.D50cm rtol=0.2

#     @test snow_depth_julia   ≈ nmr_sub.SNOWDEP  rtol=0.3
#     @test snow_density_julia ≈ nmr_sub.SNOWDENS rtol=0.2
# end

#── Visual comparisons — run manually (not in CI) ─────────────────────────────
# Set plot_year (e.g. 2013) and/or plot_month (1–12) to zoom in.
# Leave as `nothing` to plot the full 2013 run.
plot_year  = nothing   # e.g. 2014
plot_month = nothing   # e.g. 3 (March)

const PLOTS_AVAILABLE = try
    @eval using Plots
    true
catch
    @info "Plots not available — skipping visualization"
    false
end

PLOTS_AVAILABLE && let
    t_full = collect(range(DateTime(2013, 1, 1), step=Hour(1), length=NDAYS * 24))

    # Build hourly index mask
    if !isnothing(plot_year) && !isnothing(plot_month)
        title_suffix = " — $(Dates.monthname(plot_month)) $plot_year"
        hmask = findall(i -> year(t_full[i]) == plot_year && month(t_full[i]) == plot_month,
            eachindex(t_full))
    elseif !isnothing(plot_month)
        title_suffix = " — $(Dates.monthname(plot_month)) 2013"
        hmask = findall(i -> month(t_full[i]) == plot_month, eachindex(t_full))
    else
        title_suffix = " — 2013"
        hmask = eachindex(t_full)
    end

    t = t_full[hmask]

    # Obs mask (obs is at its own irregular timestamps)
    if !isnothing(plot_year) && !isnothing(plot_month)
        omask = year.(obs.DateTime) .== plot_year .&& month.(obs.DateTime) .== plot_month
    elseif !isnothing(plot_month)
        omask = month.(obs.DateTime) .== plot_month
    else
        omask = trues(nrow(obs))
    end

    # ── Extract model slices for this window ─────────────────────────────────
    snow_depth_w = ustrip.(u"cm", micro_out.snow_depth)[hmask]
    snow_density_w = ustrip.(u"g/cm^3", micro_out.snow_density)[hmask]
    julia_swe_w = snow_depth_w .* snow_density_w   # cm water equivalent
    nmr_swe_w = nmr.SNOWDEP[hmask] .* nmr.SNOWDENS[hmask]

    julia_D5cm_w = julia_D5cm[hmask]
    julia_D20cm_w = julia_D20cm[hmask]
    julia_D50cm_w = julia_D50cm[hmask]
    julia_WC5cm_w = julia_WC5cm[hmask]
    julia_WC20cm_w = julia_WC20cm[hmask]
    julia_WC50cm_w = julia_WC50cm[hmask]

    have_10cm = "D10cm" in String.(propertynames(nmr))
    have_100cm = "D100cm" in String.(propertynames(nmr))
    julia_D10cm_w = have_10cm ? ustrip.(u"°C", micro_out.soil_temperature[:, 7])[hmask] : nothing
    julia_D100cm_w = have_100cm ? ustrip.(u"°C", micro_out.soil_temperature[:, 17])[hmask] : nothing
    julia_WC10cm_w = "WC10cm" in String.(propertynames(nmr)) ? micro_out.soil_moisture[:, 7][hmask] : nothing
    julia_WC100cm_w = "WC100cm" in String.(propertynames(nmr)) ? micro_out.soil_moisture[:, 17][hmask] : nothing

    # ── Panel a: Snow ─────────────────────────────────────────────────────────
    pa1 = plot(t, nmr.SNOWDEP[hmask], label="NicheMapR", title="Snow depth (cm)", ylabel="cm")
    plot!(pa1, t, snow_depth_w, label="Julia", color=:black)
    plot!(pa1, obs.DateTime[omask], obs.SNWD_mm[omask] .* 2.54,
        label="obs", color=:red, ms=1)

    pa2 = plot(t, nmr_swe_w, label="NicheMapR", title="Snow water equiv. (cm w.e.)", ylabel="cm")
    plot!(pa2, t, julia_swe_w, label="Julia", color=:black)
    if "WTEQ_in" in String.(propertynames(obs))
        # WTEQ_in values are in inches (column name is misleading); ×2.54 → cm
        plot!(pa2, obs.DateTime[omask], obs.WTEQ_in[omask] .* 2.54,
            label="obs", color=:red, ms=1)
    end

    pa3 = plot(t, nmr.SNOWDENS[hmask], label="NicheMapR", title="Snow density (g/cm³)", ylabel="g/cm³")
    plot!(pa3, t, snow_density_w, label="Julia", color=:black)

    panel_snow = plot(pa1, pa2, pa3; layout=(3, 1), size=(900, 750),
        plot_title="Snow$title_suffix", link=:x)
    display(panel_snow)

    # # ── Panel a2: Snow node temperatures (separate panels per depth) ───────────
    # snowtemp_path = joinpath(datadir, "nmr_snowtemp.csv")

    # if isfile(snowtemp_path)
    #     nmr_st = DataFrame(CSV.File(snowtemp_path))
    #     nmr_st_w = nmr_st[hmask, :]

    #     julia_snow_temp = micro_out.snow_temperature  # K
    #     julia_sn_w = [ustrip.(u"°C", julia_snow_temp[hmask, k]) for k in 1:8]

    #     node_depths_cm = [300, 200, 100, 50, 20, 10, 5, 2]
    #     nmr_cols = [:SN1, :SN2, :SN3, :SN4, :SN5, :SN6, :SN7, :SN8]

    #     colors_sn = palette(:viridis, 10)[2:9]

    #     snow_panels = []

    #     # Skip deepest node (SN1 = 300 cm → k = 1)
    #     for k in 2:8
    #         p = plot(t,
    #             Float64.(nmr_st_w[!, nmr_cols[k]]);
    #             label="NMR",
    #             color=:red,
    #             lw=1.5,
    #             title="Snow temp $(node_depths_cm[k]) cm (°C)",
    #             ylabel="°C")

    #         plot!(p,
    #             t,
    #             julia_sn_w[k];
    #             label="Julia",
    #             color=:black,
    #             lw=1.5)

    #         push!(snow_panels, p)
    #     end

    #     # Soil surface panel
    #     if "SSOIL" in names(nmr_st_w)
    #         p0 = plot(t,
    #             Float64.(nmr_st_w.SSOIL),
    #             label="NMR soil surf",
    #             color=:red,
    #             lw=1.5,
    #             title="Soil surface temperature (°C)",
    #             ylabel="°C")

    #         plot!(p0,
    #             t,
    #             ustrip.(u"°C", micro_out.soil_temperature[hmask, 1]);
    #             label="Julia soil surf",
    #             color=:black,
    #             lw=1.5)

    #         pushfirst!(snow_panels, p0)
    #     end

    #     panel_snow = plot(
    #         snow_panels...;
    #         layout=(4, 2),
    #         size=(1100, 700),
    #         plot_title="Snow node temperatures (excluding 300 cm)$title_suffix",
    #         link=:x
    #     )

    #     display(panel_snow)
    # else
    #     println("INFO: nmr_snowtemp.csv not found — skipping snow node temperature plot.")
    # end

    # ── Panel b: Soil temperature ─────────────────────────────────────────────
    temp_panels = []

    pb1 = plot(t, nmr.D5cm[hmask], label="NicheMapR", title="Soil temp 5 cm (°C)", ylabel="°C")
    plot!(pb1, t, julia_D5cm_w, label="Julia", color=:black)
    plot!(pb1, obs.DateTime[omask], obs.STO_5cm[omask], label="obs", color=:red, ms=1)
    push!(temp_panels, pb1)

    if have_10cm
        pb2 = plot(t, nmr.D10cm[hmask], label="NicheMapR", title="Soil temp 10 cm (°C)", ylabel="°C")
        plot!(pb2, t, julia_D10cm_w, label="Julia", color=:black)
        "STO_10cm" in String.(propertynames(obs)) && plot!(pb2, obs.DateTime[omask], obs.STO_10cm[omask], label="obs", color=:red, ms=1)
        push!(temp_panels, pb2)
    end

    pb3 = plot(t, nmr.D20cm[hmask], label="NicheMapR", title="Soil temp 20 cm (°C)", ylabel="°C")
    plot!(pb3, t, julia_D20cm_w, label="Julia", color=:black)
    plot!(pb3, obs.DateTime[omask], obs.STO_20cm[omask], label="obs", color=:red, ms=1)
    push!(temp_panels, pb3)

    pb4 = plot(t, nmr.D50cm[hmask], label="NicheMapR", title="Soil temp 50 cm (°C)", ylabel="°C")
    plot!(pb4, t, julia_D50cm_w, label="Julia", color=:black)
    "STO_50cm" in String.(propertynames(obs)) && plot!(pb4, obs.DateTime[omask], obs.STO_50cm[omask], label="obs", color=:red, ms=1)
    push!(temp_panels, pb4)

    if have_100cm
        pb5 = plot(t, nmr.D100cm[hmask], label="NicheMapR", title="Soil temp 100 cm (°C)", ylabel="°C")
        plot!(pb5, t, julia_D100cm_w, label="Julia", color=:black)
        "STO_100cm" in String.(propertynames(obs)) && plot!(pb5, obs.DateTime[omask], obs.STO_100cm[omask], label="obs", color=:red, ms=1)
        push!(temp_panels, pb5)
    end

    n_temp = length(temp_panels)
    panel_temp = plot(temp_panels...; layout=(n_temp, 1), size=(900, 250 * n_temp),
        plot_title="Soil temperature$title_suffix", link=:x)
    display(panel_temp)

    # ── Panel c: Soil moisture ────────────────────────────────────────────────
    moist_panels = []

    pc1 = plot(t, nmr.WC5cm[hmask], label="NicheMapR", title="Soil moisture 5 cm (m³/m³)", ylabel="m³/m³")
    plot!(pc1, t, julia_WC5cm_w, label="Julia", color=:black)
    plot!(pc1, obs.DateTime[omask], obs.SMS_5cm[omask] ./ 100.0, label="obs", color=:red, ms=1)
    push!(moist_panels, pc1)

    if "WC10cm" in String.(propertynames(nmr))
        pc2 = plot(t, nmr.WC10cm[hmask], label="NicheMapR", title="Soil moisture 10 cm (m³/m³)", ylabel="m³/m³")
        plot!(pc2, t, julia_WC10cm_w, label="Julia", color=:black)
        "SMS_10cm" in String.(propertynames(obs)) && plot!(pc2, obs.DateTime[omask], obs.SMS_10cm[omask] ./ 100.0, label="obs", color=:red, ms=1)
        push!(moist_panels, pc2)
    end

    pc3 = plot(t, nmr.WC20cm[hmask], label="NicheMapR", title="Soil moisture 20 cm (m³/m³)", ylabel="m³/m³")
    plot!(pc3, t, julia_WC20cm_w, label="Julia", color=:black)
    "SMS_20cm" in String.(propertynames(obs)) && plot!(pc3, obs.DateTime[omask], obs.SMS_20cm[omask] ./ 100.0, label="obs", color=:red, ms=1)
    push!(moist_panels, pc3)

    pc4 = plot(t, nmr.WC50cm[hmask], label="NicheMapR", title="Soil moisture 50 cm (m³/m³)", ylabel="m³/m³")
    plot!(pc4, t, julia_WC50cm_w, label="Julia", color=:black)
    "SMS_50cm" in String.(propertynames(obs)) && plot!(pc4, obs.DateTime[omask], obs.SMS_50cm[omask] ./ 100.0, label="obs", color=:red, ms=1)
    push!(moist_panels, pc4)

    if "WC100cm" in String.(propertynames(nmr))
        pc5 = plot(t, nmr.WC100cm[hmask], label="NicheMapR", title="Soil moisture 100 cm (m³/m³)", ylabel="m³/m³")
        plot!(pc5, t, julia_WC100cm_w, label="Julia", color=:black)
        "SMS_100cm" in String.(propertynames(obs)) && plot!(pc5, obs.DateTime[omask], obs.SMS_100cm[omask] ./ 100.0, label="obs", color=:red, ms=1)
        push!(moist_panels, pc5)
    end

    n_moist = length(moist_panels)
    panel_moist = plot(moist_panels...; layout=(n_moist, 1), size=(900, 250 * n_moist),
        plot_title="Soil moisture$title_suffix", link=:x)
    display(panel_moist)
end
